hash-format = "sha256"

[[files]]
file = "README.md"
hash = "0c2d2f657ef368dfe2bc475db8f189a3f7fa28766f1787c11db441dd657dddb2"

[[files]]
file = "SkyBlock Enhanced/OfficialConfigs/SkyBlock_Enhanced_Default_Configs.zip"
hash = "c699e303f73a7fbaa20502246ebf88981ec58d4137324fa2689f200cc8b2f472"

[[files]]
file = "SkyBlock Enhanced/modpack_info.json"
hash = "7b0edf148b70736257e86dd8b34602cb4c9e649b9fa6f4c895f4a65a4e3c0a27"

[[files]]
file = "icon.png"
hash = "51576c0fa92902a17f8484e56a89daf68489e71e39ea98717502b7eac34ad8b2"

[[files]]
file = "mods/3dskinlayers.pw.toml"
hash = "db50e8c3fa1548b8bacf044d8871237b02de6e39b08b7e6f9ce139af9d7ca625"
metafile = true

[[files]]
file = "mods/architectury-api.pw.toml"
hash = "a463f60553d19dc6cdb468e8a0f9faa73fd6694f8eb87fe11532c81e9c908dcf"
metafile = true

[[files]]
file = "mods/auth-me.pw.toml"
hash = "544409002b00cfe520c66f8c84d69b073c8e193ea20493bfacafbf93701c889d"
metafile = true

[[files]]
file = "mods/badoptimizations.pw.toml"
hash = "2a591dc20bd77776dfb60714a83058719a81301d2dfcacdc96e81136c5611dd9"
metafile = true

[[files]]
file = "mods/bazaar-utils.pw.toml"
hash = "d044e72b177d5668200c67f102f408041fa5607c7ec97d50967c24e8d621e5be"
metafile = true

[[files]]
file = "mods/betterf3.pw.toml"
hash = "dc1578a021bb4e5699524f5216d8aa9b08c9d30bfbfe0bc72bf07f5391c3f3b5"
metafile = true

[[files]]
file = "mods/c2me-fabric.pw.toml"
hash = "39d2695bf316d7d48d21da0ae6b38ea3e74c47c3b07c93bbade4dd753df90321"
metafile = true

[[files]]
file = "mods/chatpatches.pw.toml"
hash = "5001fa841ab7e909190378587665890ba5f15a1373f2bf360393984d7606e2e1"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "13ae813426f52226d8363499d722df0933e84534f216eef127c198c18bcdbb6b"
metafile = true

[[files]]
file = "mods/cookies-mod.pw.toml"
hash = "fef0419fff229d501ff9827191c1cf87634bc3d352eadf6802be34f532252c0b"
metafile = true

[[files]]
file = "mods/cubes-without-borders.pw.toml"
hash = "a90139b002d632ba9256cb3e7e877945bf8e3afa5b191d1adc83c5e3eb72da4c"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "f91706e274edf8016379c50d22d607dc344754f051b7cf30835c0e758ba995e0"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "191d25d191a31ada2de9916f4f6ad9b339c1775b104ea4046e414422a09888bc"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "f217a0233c8aef84e914e1f8e90718be2496a923725215190d375ab3140379ab"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "fbf9806c22ee5bccbe08f7dec15b742f5ae3a70caf186d6dce0d42f28790f559"
metafile = true

[[files]]
file = "mods/firmament.pw.toml"
hash = "55c6219168abc7a8fa728eed5aa600fb897748b6eb541990f1ed9f70c41fd1bd"
metafile = true

[[files]]
file = "mods/fzzy-config.pw.toml"
hash = "c3741eb99da1676db710022999844ad608687b2008743403e840b3e9df8c5cba"
metafile = true

[[files]]
file = "mods/gamma-utils.pw.toml"
hash = "772b4329e035c8b0dbb728ab5c005bca5b5ea398880f7ab2edbec8a1414e8347"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
hash = "2449e4f29f167ff8453e67d0d4fc47294523e2ca9dce022d1a5670cd2ed49808"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "623f91f5cb2cfe0e7c3a6fc48ae5984dfad62e85389e2567ab5421f7d9d02c51"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "29bc0f585963a84e1f78af8a1ab779e34dcc4c1657190297bca9cd95aeb90d36"
metafile = true

[[files]]
file = "mods/modelfix.pw.toml"
hash = "14800fc12fd4b92497c0f26455523783bdf59194233bdaa71d4864b3d436929a"
metafile = true

[[files]]
file = "mods/modern-warp-menu.pw.toml"
hash = "8e33bb462136121fda9d6b9d3d943cf9d61796ad89af728b76a6c015fa5587da"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "e48fadea92533a14b45d8fb64ed10e5942ee90bba874589822a766a6d47930b2"
metafile = true

[[files]]
file = "mods/moreculling.pw.toml"
hash = "8d250e4781a41beb98270b2f36e042415067f92081c6fcf843d7ea89a61b4cdc"
metafile = true

[[files]]
file = "mods/no-chat-reports.pw.toml"
hash = "e94c47d7679c5a6a4a3deccaa7bba8f7c3961a70f6c03c32adc809d7135c87cc"
metafile = true

[[files]]
file = "mods/packcore.pw.toml"
hash = "9472b84d3dbe607a4845f102842571be15bb8ede7c9c1ff084725f62cd6ee959"
metafile = true

[[files]]
file = "mods/particle-core.pw.toml"
hash = "35806b3163ce2405e55abcda320300fa7a133f2f67ad453c7d3631d68a5ba0e2"
metafile = true

[[files]]
file = "mods/placeholder-api.pw.toml"
hash = "799419e64ed42a8175333c541a08995fc4d84a2c6000877f60262fe55892e3ff"
metafile = true

[[files]]
file = "mods/reeses-sodium-options.pw.toml"
hash = "55a727cabdd9d6e84fb0232b49d0dfa207751002e7f1f63b959baa35e2f29868"
metafile = true

[[files]]
file = "mods/rei.pw.toml"
hash = "971c19f9973cfbe98103f091734b25e9dfc5c7dba7cb3905021133ee6653abc9"
metafile = true

[[files]]
file = "mods/sbt.pw.toml"
hash = "34fa3a4840745f08b4c2013f0c437530d47a7afed589aeeb7e4bd442aa1c13b4"
metafile = true

[[files]]
file = "mods/scalablelux.pw.toml"
hash = "3975d8351b1a246c8c2e13251ea4f86fee525ae772a51927c37407a88b03defb"
metafile = true

[[files]]
file = "mods/skyblock-profile-viewer.pw.toml"
hash = "f3dcb8786b77e2b28421cbca570e4cdfb8e1ff133b851f89512ff6a704050a87"
metafile = true

[[files]]
file = "mods/skyblocker-liap.pw.toml"
hash = "12a93cac10964455969541d5e78fbd8c0edfa4b307c079cb607c5656c203c71e"
metafile = true

[[files]]
file = "mods/skyhanni.pw.toml"
hash = "1976fd178b499a4540b5e31aee8f2e266aa2ed7b8fd9a51786bb172b3edd2a88"
metafile = true

[[files]]
file = "mods/skyocean.pw.toml"
hash = "eab01992b7091aa8000fda57a5649f24556dd21dfa29f4ca5d496de67dcf5b88"
metafile = true

[[files]]
file = "mods/sodium-extra.pw.toml"
hash = "abe9878dcb237d56e2ba70c17db8c721c6c2b8e62b241bc333539d5bc6be938f"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "700caca572649f238e804258f79d25969031be3e1b01d0384eb54a13200caba6"
metafile = true

[[files]]
file = "mods/threadtweak.pw.toml"
hash = "ff0d87064f466d6dfa5151178cb805cea4169a6e85f47913b462758262a78024"
metafile = true

[[files]]
file = "mods/vmp-fabric.pw.toml"
hash = "dee7712131e72105b1a9dafe6e103308e33023a4a48ec3b3868298d8d6c4ed6c"
metafile = true

[[files]]
file = "mods/wavey-capes.pw.toml"
hash = "01586a21c55e79e09cbe5ad774c2002cbe8f48d0c96868c8f889ce57b5acf2d1"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "dc66d444a8cfd427c3c05d47babcc43f7fca842c1d7731116bd07c7d88441edc"
metafile = true

[[files]]
file = "mods/zoomify.pw.toml"
hash = "c9a5dca078d983e94d629ca4bf402fff78e364e5b5365ff43373d77eec268432"
metafile = true

[[files]]
file = "resourcepacks/default-dark-mode.pw.toml"
hash = "4d54a64972ea89e49f314867802406f7ca73fa738ff35320c938f980ac0c8f4b"
metafile = true

[[files]]
file = "resourcepacks/furfsky-reborn.pw.toml"
hash = "e11d17602a3933fd6fe9582d900ddbbd1f9e6d65d751931e0f3bfa3e85592fe8"
metafile = true

[[files]]
file = "resourcepacks/hypixel-plus.pw.toml"
hash = "bbc5a21ac06cbfad45153cc7448a8b24cc9f6e72f6dd9b7329c7a8fe7b101000"
metafile = true
