hash-format = "sha256"

[[files]]
file = "SkyBlock Enhanced/modpack_info.json"
hash = "82dd4b8012ff07cfafc2ddbf291520c4195847fbaa4de768a5d775ce9795f42f"

[[files]]
file = "mods/badoptimizations.pw.toml"
hash = "57c157ebf3f36495fa14668c3906e70726a83564c7d0071507fc85baa106626c"
metafile = true

[[files]]
file = "mods/c2me-fabric.pw.toml"
hash = "39d2695bf316d7d48d21da0ae6b38ea3e74c47c3b07c93bbade4dd753df90321"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "13ae813426f52226d8363499d722df0933e84534f216eef127c198c18bcdbb6b"
metafile = true

[[files]]
file = "mods/cubes-without-borders.pw.toml"
hash = "a90139b002d632ba9256cb3e7e877945bf8e3afa5b191d1adc83c5e3eb72da4c"
metafile = true

[[files]]
file = "mods/cursor-anchor.pw.toml"
hash = "3269c873711d07af7eb3b62a5046f11d6bcb4165133d132ff41abce32bc564e4"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "138e20f1257a5fed553a89c8701a5c15f22986a2e8b77c87bea3eafa59995920"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "528200f74061ca4d9ca1e1e65d932fd7fd49a071cef36912f117a4b2a0a537cf"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "967a780be97bec40b8bca4945a053ee4fbd05d58e218c4fb803959ac0d0c7f08"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "fbf9806c22ee5bccbe08f7dec15b742f5ae3a70caf186d6dce0d42f28790f559"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
hash = "2449e4f29f167ff8453e67d0d4fc47294523e2ca9dce022d1a5670cd2ed49808"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "5773d3e597b591a9cd1d6d0808aa5820ecfef9f95c3ebe88aae485980f032e8a"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "e48fadea92533a14b45d8fb64ed10e5942ee90bba874589822a766a6d47930b2"
metafile = true

[[files]]
file = "mods/moreculling.pw.toml"
hash = "8d250e4781a41beb98270b2f36e042415067f92081c6fcf843d7ea89a61b4cdc"
metafile = true

[[files]]
file = "mods/no-chat-reports.pw.toml"
hash = "e94c47d7679c5a6a4a3deccaa7bba8f7c3961a70f6c03c32adc809d7135c87cc"
metafile = true

[[files]]
file = "mods/packcore.pw.toml"
hash = "de4b5539127487f894ecb7b2455f74d44e86c448128f7de8133c92ae98d7a5d3"
metafile = true

[[files]]
file = "mods/placeholder-api.pw.toml"
hash = "37d94eccb60749412f669a737642a603eb549225c9a49c45320a0ca097dfc513"
metafile = true

[[files]]
file = "mods/scalablelux.pw.toml"
hash = "3975d8351b1a246c8c2e13251ea4f86fee525ae772a51927c37407a88b03defb"
metafile = true

[[files]]
file = "mods/skyblocker-liap.pw.toml"
hash = "06e2c0b5ee7c9f23dc8cf78f750ccbe30f6491bdb355191525f450e3422283da"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "700caca572649f238e804258f79d25969031be3e1b01d0384eb54a13200caba6"
metafile = true

[[files]]
file = "mods/threadtweak.pw.toml"
hash = "ff0d87064f466d6dfa5151178cb805cea4169a6e85f47913b462758262a78024"
metafile = true

[[files]]
file = "mods/vmp-fabric.pw.toml"
hash = "dee7712131e72105b1a9dafe6e103308e33023a4a48ec3b3868298d8d6c4ed6c"
metafile = true

[[files]]
file = "resourcepacks/hypixel-plus.pw.toml"
hash = "bbc5a21ac06cbfad45153cc7448a8b24cc9f6e72f6dd9b7329c7a8fe7b101000"
metafile = true
