hash-format = "sha256"

[[files]]
file = "README.md"
hash = "101f76b8cc59ab79c170fb5054e129800e7c867bc6046bc72f791ce8d7f7e5cc"

[[files]]
file = "SkyBlock Enhanced/OfficialConfigs/SE-1080p_screen_resolution-Default_ConfigsV2.zip"
hash = "6baa78c6f85142de57dc71d70088dda72f2fd4b4aafc8b9c80b2bfc6779740e5"

[[files]]
file = "SkyBlock Enhanced/OfficialConfigs/SE-1440p_screen_resolution-Default_ConfigsV2.zip"
hash = "f295c508eb7c00f554bed68307461f28d23aebf5b26f366d97c16dd90f467b9c"

[[files]]
file = "SkyBlock Enhanced/OfficialConfigs/SE-4k_screen_resolution-Default_ConfigsV2.zip"
hash = "fad3c61c1b8e4b5e03dec6cab5614d4a89f0a3df0789cbe0b27b8b301b406361"

[[files]]
file = "SkyBlock Enhanced/dialog-content.md"
hash = "a2e7194009a42c4f7952ea4cf3b3ee8ca2e5e8be7447e033bb4870f6fd6868dc"

[[files]]
file = "SkyBlock Enhanced/modpack_info.json"
hash = "dcee605dbb85e64223c6f41db7a6882eefa1e85e6ffc5d3402fb2f7afcc88125"

[[files]]
file = "icon.png"
hash = "51576c0fa92902a17f8484e56a89daf68489e71e39ea98717502b7eac34ad8b2"

[[files]]
file = "mods/3dskinlayers.pw.toml"
hash = "e5e0885e614d4d22bda2248d3688b7ba6559fe1ca947b416124e61c0aaa70c79"
metafile = true

[[files]]
file = "mods/architectury-api.pw.toml"
hash = "a463f60553d19dc6cdb468e8a0f9faa73fd6694f8eb87fe11532c81e9c908dcf"
metafile = true

[[files]]
file = "mods/auth-me.pw.toml"
hash = "544409002b00cfe520c66f8c84d69b073c8e193ea20493bfacafbf93701c889d"
metafile = true

[[files]]
file = "mods/badoptimizations.pw.toml"
hash = "1e59464196bd2a0cb5dcc4eb6014e323982e993c68c0f0173ff95b58ceed366e"
metafile = true

[[files]]
file = "mods/bazaar-utils.pw.toml"
hash = "43c7219abc715ed17b2747d97cf59885dd546c08a7595014031be56c0ffb1c55"
metafile = true

[[files]]
file = "mods/betterf3.pw.toml"
hash = "dc1578a021bb4e5699524f5216d8aa9b08c9d30bfbfe0bc72bf07f5391c3f3b5"
metafile = true

[[files]]
file = "mods/c2me-fabric.pw.toml"
hash = "39d2695bf316d7d48d21da0ae6b38ea3e74c47c3b07c93bbade4dd753df90321"
metafile = true

[[files]]
file = "mods/centered-crosshair.pw.toml"
hash = "0f25d3b1f14ab490edf3cbbf05029e3237eb0213a9e25e10b357cb91a7662ede"
metafile = true

[[files]]
file = "mods/chatpatches.pw.toml"
hash = "91bfb35359acf9f62916ff73bea5f236a138951d5426aae41b8417f1b5ee0b93"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "13ae813426f52226d8363499d722df0933e84534f216eef127c198c18bcdbb6b"
metafile = true

[[files]]
file = "mods/continuity.pw.toml"
hash = "278a349024e41e039f9f4a278532b56d1774cd2f7fde04f2cff298f3e085d995"
metafile = true

[[files]]
file = "mods/cubes-without-borders.pw.toml"
hash = "a90139b002d632ba9256cb3e7e877945bf8e3afa5b191d1adc83c5e3eb72da4c"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "33d22f0f1f007754a2b13b267c395afb577616fcbb29b7473a06dca256f23803"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "275a1ecb11bde12b8c4c713b533230c75bc47bcffc590c5299287263d828c9b3"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "f217a0233c8aef84e914e1f8e90718be2496a923725215190d375ab3140379ab"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "fbf9806c22ee5bccbe08f7dec15b742f5ae3a70caf186d6dce0d42f28790f559"
metafile = true

[[files]]
file = "mods/firmament.pw.toml"
hash = "560a89ec786af0f3290d36dbc729b6ddb5ed6bfc3e4c63679eaee027e524d2a8"
metafile = true

[[files]]
file = "mods/fzzy-config.pw.toml"
hash = "fbefd845bd130883357c1ad3765bef4f1acc89dfd362e52358856e10315dc386"
metafile = true

[[files]]
file = "mods/gamma-utils.pw.toml"
hash = "772b4329e035c8b0dbb728ab5c005bca5b5ea398880f7ab2edbec8a1414e8347"
metafile = true

[[files]]
file = "mods/hypixel-mod-api.pw.toml"
hash = "42253042d1ceef54a447e284f35e83dae016d9baf626186bb2df91786ea68502"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
hash = "5d6f1406628a792f100454fb8cbf3ad70a76fe58e0bdb09df3cf5e8d86e878a7"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "623f91f5cb2cfe0e7c3a6fc48ae5984dfad62e85389e2567ab5421f7d9d02c51"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "29bc0f585963a84e1f78af8a1ab779e34dcc4c1657190297bca9cd95aeb90d36"
metafile = true

[[files]]
file = "mods/modelfix.pw.toml"
hash = "14800fc12fd4b92497c0f26455523783bdf59194233bdaa71d4864b3d436929a"
metafile = true

[[files]]
file = "mods/modern-warp-menu.pw.toml"
hash = "2ca9451fe6f573a694a23a6a1f4a69e9ab89db13ca62d36fb15fe255085d650d"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "e48fadea92533a14b45d8fb64ed10e5942ee90bba874589822a766a6d47930b2"
metafile = true

[[files]]
file = "mods/moreculling.pw.toml"
hash = "8d250e4781a41beb98270b2f36e042415067f92081c6fcf843d7ea89a61b4cdc"
metafile = true

[[files]]
file = "mods/no-chat-reports.pw.toml"
hash = "e94c47d7679c5a6a4a3deccaa7bba8f7c3961a70f6c03c32adc809d7135c87cc"
metafile = true

[[files]]
file = "mods/no-double-sneak.pw.toml"
hash = "db834fc92e54a4c688548de39cc0953a51fa9a56506a56ea2bbbbf6a2edf9c6a"
metafile = true

[[files]]
file = "mods/no-resource-pack-warnings.pw.toml"
hash = "da9ac20bdc1caa50ebec291429638780924e8a5060ec39abe085c7e6182b3a6f"
metafile = true

[[files]]
file = "mods/packcore.pw.toml"
hash = "2c1d8406e638571fe6929152825edd4a762d4d3fdef7995b9bc9066097d954de"
metafile = true

[[files]]
file = "mods/particle-core.pw.toml"
hash = "35806b3163ce2405e55abcda320300fa7a133f2f67ad453c7d3631d68a5ba0e2"
metafile = true

[[files]]
file = "mods/placeholder-api.pw.toml"
hash = "799419e64ed42a8175333c541a08995fc4d84a2c6000877f60262fe55892e3ff"
metafile = true

[[files]]
file = "mods/reeses-sodium-options.pw.toml"
hash = "55a727cabdd9d6e84fb0232b49d0dfa207751002e7f1f63b959baa35e2f29868"
metafile = true

[[files]]
file = "mods/rei-search-bar-calculations.pw.toml"
hash = "59bc278d0982ec0943230822a4b7692ac0714272a04180d928c3eef99a3008b9"
metafile = true

[[files]]
file = "mods/rei.pw.toml"
hash = "f04be730a6dde5e7e3ce302260bc1a456a4e0fd57a00755d3992f9c0daafd21d"
metafile = true

[[files]]
file = "mods/sbt.pw.toml"
hash = "3709c90879c9c65e6fb3cc6a288ba2da0e214f60f17b1721d14133548e4eecd2"
metafile = true

[[files]]
file = "mods/scalablelux.pw.toml"
hash = "3975d8351b1a246c8c2e13251ea4f86fee525ae772a51927c37407a88b03defb"
metafile = true

[[files]]
file = "mods/scaleme.pw.toml"
hash = "5d1aa36dd881099e85fefe006bc68559e44930dedd376c2404c5d643fc4e436d"
metafile = true

[[files]]
file = "mods/sk1er-scrollable-tooltips.pw.toml"
hash = "7df906c0f5ee6d8bc2ce16eeb143f931897fb9705cc4bc5bba7e251f6ef9fd72"
metafile = true

[[files]]
file = "mods/skyblock-profile-viewer.pw.toml"
hash = "36df4a1f776862baa6edc0ac1874db3dc5d4c1af0911ad5bae34eb2ed18da173"
metafile = true

[[files]]
file = "mods/skyblockaddons-unofficial.pw.toml"
hash = "7623847efa8147522be3e5bbaf42826641a552f5a9bfbc764a7ec8ff01af02a1"
metafile = true

[[files]]
file = "mods/skyblocker-liap.pw.toml"
hash = "d4d67283238880ef78cf641bf55441253887ff3978bcd16fb14e8f47afd382fc"
metafile = true

[[files]]
file = "mods/skyhanni.pw.toml"
hash = "e6c686118b14055e26057f883bc8f534876e2efd84588795f39f87071490de11"
metafile = true

[[files]]
file = "mods/skyocean.pw.toml"
hash = "cd88f3f305e3bd14545a510172c8756e94f733840099b2faf1204f7ef6079ecc"
metafile = true

[[files]]
file = "mods/sodium-extra.pw.toml"
hash = "abe9878dcb237d56e2ba70c17db8c721c6c2b8e62b241bc333539d5bc6be938f"
metafile = true

[[files]]
file = "mods/sodium-shadowy-path-blocks.pw.toml"
hash = "b91aa8ca577a8397296c43e06f54e8246cbdacd44afa08ab6188323c441ac359"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "700caca572649f238e804258f79d25969031be3e1b01d0384eb54a13200caba6"
metafile = true

[[files]]
file = "mods/sound-controller.pw.toml"
hash = "5eb6c30f71d4b90b393612c6ca74e157b5544320f652bb397de165486685679a"
metafile = true

[[files]]
file = "mods/threadtweak.pw.toml"
hash = "ff0d87064f466d6dfa5151178cb805cea4169a6e85f47913b462758262a78024"
metafile = true

[[files]]
file = "mods/vistas.pw.toml"
hash = "633434fd0533b75e3ead8e8d6b44d327ca70a9e4c3a3a72b6b7f46d196222673"
metafile = true

[[files]]
file = "mods/vmp-fabric.pw.toml"
hash = "dee7712131e72105b1a9dafe6e103308e33023a4a48ec3b3868298d8d6c4ed6c"
metafile = true

[[files]]
file = "mods/wavey-capes.pw.toml"
hash = "09a90457d22e51bd4612635639184596dc87ffa52a4900139d33ccb09a31b26b"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "dc66d444a8cfd427c3c05d47babcc43f7fca842c1d7731116bd07c7d88441edc"
metafile = true

[[files]]
file = "mods/zoomify.pw.toml"
hash = "c9a5dca078d983e94d629ca4bf402fff78e364e5b5365ff43373d77eec268432"
metafile = true

[[files]]
file = "resourcepacks/Warp Menu - New Islands.zip"
hash = "58c2127f511d6cb9a5ede38c506e6ed5c3158a273f9a403ba84a25a3de05e899"

[[files]]
file = "resourcepacks/furfsky-reborn.pw.toml"
hash = "b56bb632dc2e82e66b7f477ae94b3586a18e9727996409e509e51a742a0f22a1"
metafile = true

[[files]]
file = "resourcepacks/hypixel-plus.pw.toml"
hash = "bbc5a21ac06cbfad45153cc7448a8b24cc9f6e72f6dd9b7329c7a8fe7b101000"
metafile = true

[[files]]
file = "resourcepacks/skyblock-dark-ui.pw.toml"
hash = "b40fc70081e8fe6283388be3f287eaffe3b18b74d633a923df1156159a260e6b"
metafile = true
