hash-format = "sha256"

[[files]]
file = ".github/ISSUE_TEMPLATE/bug_report.yml"
hash = "aa6bb01ceed3ec15078be129145adb074798e7abf700bc2dabbbebcd89cd16db"

[[files]]
file = ".github/ISSUE_TEMPLATE/configuration.yml"
hash = "87f3dfb7d519789003273724e0171759ae230af6960e775f9770e2762b3b3ffe"

[[files]]
file = ".github/ISSUE_TEMPLATE/mod_request.yml"
hash = "8433d4bebb131697cb176454e6cd2961302818d06ad3451e57ed9ead80d0d95a"

[[files]]
file = ".github/ISSUE_TEMPLATE/performance_issue.yml"
hash = "1fbe068f4502e6216a50ccc22c2d4596a1f6ab035026fdf5061070f26c53c1be"

[[files]]
file = ".github/ISSUE_TEMPLATE/suggestion.yml"
hash = "bcbbdd30b241548561a90017c8f58b9c2685f59a3a4dc74b97bcdedea0363ea1"

[[files]]
file = "LICENSE"
hash = "1eb85fc97224598dad1852b5d6483bbcf0aa8608790dcc657a5a2a761ae9c8c6"

[[files]]
file = "README.md"
hash = "8a40826c52327594f49c9ee03237326549e15c7b8a173d83194763b4d9cfeaf8"

[[files]]
file = "Skyblock Enhanced/OfficialConfigs/Normal 1080p Configs.zip"
hash = "0616063faf41854a5d2c9ee9b2b594afe95100c4ecc8a9e6dfc3b7bff6361a38"

[[files]]
file = "Skyblock Enhanced/OfficialConfigs/Normal 1440p Configs.zip"
hash = "d0cc29fd2c46100f0ffc04228ab1328b165f7273733b3bd13ccd5ca0587c1a33"

[[files]]
file = "Skyblock Enhanced/modpack_info.json"
hash = "618ef80b3275361a9969c455e021c9cbc75768ab265be9a730f54d5f6df529c8"

[[files]]
file = "icon.png"
hash = "1dbbfa3bb6363eff3b0cb22662d1d12000235424aaea379d6ee3e14eff80eb68"

[[files]]
file = "mods/Scrollable Tooltips-1.4 (1.8.9).jar"
hash = "0f1fdcc3cafbd4c2d44e5b015ed62b015a04e2a93f7a61c866f1248ac104fd25"

[[files]]
file = "mods/chatting.pw.toml"
hash = "acd9848cd9221f74ff71570aca0f44251003de470e6a416fc5a25fd34dbe3749"
metafile = true

[[files]]
file = "mods/dungeons-guide.pw.toml"
hash = "e56598da647bf642a28d6d0498e9337639916424c98ac896c2f9079b67d065c4"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "9e39622e4a1d59cfc3c1eaf765631d5ea3be8320326f5de21380a320db938e9c"
metafile = true

[[files]]
file = "mods/essential.pw.toml"
hash = "adf9d1590499c8a87aefe00558e7baf5957e6807dfbf52d36f68c3e3e9459b3c"
metafile = true

[[files]]
file = "mods/fancy-warp-menu.pw.toml"
hash = "49cacb49d7c4a3db90064495e57bf711c088053f694174f5d55e55f64c70e17b"
metafile = true

[[files]]
file = "mods/foamfix.pw.toml"
hash = "da1a972b0a76c896a1b33cbb720ad5324e1238cc21e2beb3cd952088fee825e5"
metafile = true

[[files]]
file = "mods/notenoughupdates.pw.toml"
hash = "8dff3d320bc947719b676dd8b7464b2234afff47a8ed0504b2d37b0ff4151d97"
metafile = true

[[files]]
file = "mods/optibye.pw.toml"
hash = "28679b2d26a515f09fe9bf1d33f9671ca12e99680932246867e64701a5557fd8"
metafile = true

[[files]]
file = "mods/overflowparticles.pw.toml"
hash = "f2b0cdec84586309e24cc2e90de64189a2a2189c4563b7ad0d3f58e816766f5e"
metafile = true

[[files]]
file = "mods/packcore.pw.toml"
hash = "acdee560bdc83611034b9a14bd22597f9c8d74d5a4fcc86c479a0b1652cd74d8"
metafile = true

[[files]]
file = "mods/patcher.pw.toml"
hash = "8a5f2cf7f332936a6ef838a08bd1841ecb5af85122f11c3725b4b68a07a15b41"
metafile = true

[[files]]
file = "mods/phosphorlegacyforge.pw.toml"
hash = "33cbbf1fde609de8acde6dacb3c77374fa6463b96e10312247da8a19c99ef64e"
metafile = true

[[files]]
file = "mods/polished-gui.pw.toml"
hash = "b829772cfe753f6c7c03f19271daf61dfb91d499bac791ba872de27383cb49b3"
metafile = true

[[files]]
file = "mods/polysprint.pw.toml"
hash = "8801c32386ce295df8dc1fd2a99acebbf53f3b4cee239bb7d3c11ea1b5cea57f"
metafile = true

[[files]]
file = "mods/redirectionor.pw.toml"
hash = "b4a8552dc1bbba7775913f1bfdc06f154e63392541cceccbe5b100c725e20006"
metafile = true

[[files]]
file = "mods/skyblockaddons-unofficial.pw.toml"
hash = "ac298d72c4dfd2abb3d365ec303f156fed1b442a03059d6643a166e7c0f37407"
metafile = true

[[files]]
file = "mods/skyhanni.pw.toml"
hash = "e04198250ca79a336376bc902ba4f9e7989450befb3e70a9e920e064070cd09f"
metafile = true

[[files]]
file = "mods/skytils.pw.toml"
hash = "d6bfd166d44225388389755d6807cb58eff441df2caf5019d848019650be08bb"
metafile = true

[[files]]
file = "mods/veloxcaelo.pw.toml"
hash = "54c0246dc7d56478af21dc28e147274481f76e551f0e1058280f51704f72ad57"
metafile = true

[[files]]
file = "resourcepacks/default-dark-mode.pw.toml"
hash = "89801dfa3dcf00e007fbe5790d7940c568a00889658248db44b02ccf50517fd3"
metafile = true

[[files]]
file = "resourcepacks/faithful-32x.pw.toml"
hash = "a2fc236c1d93040533f15238dc30314b69619898b9723dc6400e6cc6c8b9be37"
metafile = true

[[files]]
file = "resourcepacks/hypixel-plus.pw.toml"
hash = "ffb22d1ced0fd847edb8a65d3653723dd56d1612a3fea5bfc37c5b22e0bb818a"
metafile = true
