hash-format = "sha256"

[[files]]
file = "README.md"
hash = "101f76b8cc59ab79c170fb5054e129800e7c867bc6046bc72f791ce8d7f7e5cc"

[[files]]
file = "SkyBlock Enhanced/OfficialConfigs/SE-1080p_screen_resolution-Default_ConfigsV2.zip"
hash = "e4b9f2f72d1aec465b9ac2f57758e14fc7a26af24f0245b7d427a4b42df21f59"

[[files]]
file = "SkyBlock Enhanced/OfficialConfigs/SE-1440p_screen_resolution-Default_ConfigsV2.zip"
hash = "876607e3ebb740399de44bb2d092fb7f16d850e097252fa17170e701b4e2bac3"

[[files]]
file = "SkyBlock Enhanced/OfficialConfigs/SE-4k_screen_resolution-Default_ConfigsV2.zip"
hash = "ceebd490ab421bd1f885f37870d570e379cd441e6c94320bdf90864cfb03e9c0"

[[files]]
file = "SkyBlock Enhanced/dialog-content.md"
hash = "31b6306196467c15f02895f7fc3640dce6cb52b3c1b70615fdfb6270d0914b9e"

[[files]]
file = "SkyBlock Enhanced/modpack_info.json"
hash = "9941b910e80996835854f3c3f3b9982831d94794c24d2613e4ebfa3197a15383"

[[files]]
file = "icon.png"
hash = "51576c0fa92902a17f8484e56a89daf68489e71e39ea98717502b7eac34ad8b2"

[[files]]
file = "mods/3dskinlayers.pw.toml"
hash = "599b493a454411ad83f055f763394176a90b0c3a8a2bd3f7c50acde27fec4a79"
metafile = true

[[files]]
file = "mods/architectury-api.pw.toml"
hash = "a463f60553d19dc6cdb468e8a0f9faa73fd6694f8eb87fe11532c81e9c908dcf"
metafile = true

[[files]]
file = "mods/auth-me.pw.toml"
hash = "544409002b00cfe520c66f8c84d69b073c8e193ea20493bfacafbf93701c889d"
metafile = true

[[files]]
file = "mods/badoptimizations.pw.toml"
hash = "284a7ccf2dc6ff43378230c252323359634f2b566212924ad0f138f4203079c6"
metafile = true

[[files]]
file = "mods/bazaar-utils.pw.toml"
hash = "e8e0a01ab03fd99ddb5aa40538cbc99814a726e02bff334646c0cee56aa00887"
metafile = true

[[files]]
file = "mods/betterf3.pw.toml"
hash = "dc1578a021bb4e5699524f5216d8aa9b08c9d30bfbfe0bc72bf07f5391c3f3b5"
metafile = true

[[files]]
file = "mods/c2me-fabric.pw.toml"
hash = "39d2695bf316d7d48d21da0ae6b38ea3e74c47c3b07c93bbade4dd753df90321"
metafile = true

[[files]]
file = "mods/centered-crosshair.pw.toml"
hash = "0f25d3b1f14ab490edf3cbbf05029e3237eb0213a9e25e10b357cb91a7662ede"
metafile = true

[[files]]
file = "mods/chatpatches.pw.toml"
hash = "c5f2cc7044dc0898ed92061a26f6067cc426739684f722f80cdb4ced20b4bf2b"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "13ae813426f52226d8363499d722df0933e84534f216eef127c198c18bcdbb6b"
metafile = true

[[files]]
file = "mods/continuity.pw.toml"
hash = "278a349024e41e039f9f4a278532b56d1774cd2f7fde04f2cff298f3e085d995"
metafile = true

[[files]]
file = "mods/cubes-without-borders.pw.toml"
hash = "a90139b002d632ba9256cb3e7e877945bf8e3afa5b191d1adc83c5e3eb72da4c"
metafile = true

[[files]]
file = "mods/entityculling.pw.toml"
hash = "33d22f0f1f007754a2b13b267c395afb577616fcbb29b7473a06dca256f23803"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "12fe61275734cf8d2554d5f92af20ccb22479118b36a9a56a275ad3f4b1e13fb"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "098d6976a738658ca490cc58e9fab19f06cd1a7b23199b6f1ee108d866333e22"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "fbf9806c22ee5bccbe08f7dec15b742f5ae3a70caf186d6dce0d42f28790f559"
metafile = true

[[files]]
file = "mods/firmament.pw.toml"
hash = "28771a8e988c1936fa74948024513a22946da975ff58d8d073292889e7d51506"
metafile = true

[[files]]
file = "mods/fzzy-config.pw.toml"
hash = "122de540aa5a998cab2481e7696ca6457323f8c8322715ea9f5df8d59d4fe8f4"
metafile = true

[[files]]
file = "mods/gamma-utils.pw.toml"
hash = "d6c762a1ae9e43903416e37af42f63f1c485051b77d44c5501a2097c1149b630"
metafile = true

[[files]]
file = "mods/hypixel-mod-api.pw.toml"
hash = "42253042d1ceef54a447e284f35e83dae016d9baf626186bb2df91786ea68502"
metafile = true

[[files]]
file = "mods/immediatelyfast.pw.toml"
hash = "aff7a565699323a9319eb3791adfa5c24e230c92d947bc97714e816acb101f8a"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "623f91f5cb2cfe0e7c3a6fc48ae5984dfad62e85389e2567ab5421f7d9d02c51"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "29bc0f585963a84e1f78af8a1ab779e34dcc4c1657190297bca9cd95aeb90d36"
metafile = true

[[files]]
file = "mods/modelfix.pw.toml"
hash = "14800fc12fd4b92497c0f26455523783bdf59194233bdaa71d4864b3d436929a"
metafile = true

[[files]]
file = "mods/modern-warp-menu.pw.toml"
hash = "f3d7ec92597c87f9e0b47f70c37d54ab17623b3c1ac98fda849262da5dd84ad3"
metafile = true

[[files]]
file = "mods/modmenu.pw.toml"
hash = "e48fadea92533a14b45d8fb64ed10e5942ee90bba874589822a766a6d47930b2"
metafile = true

[[files]]
file = "mods/moreculling.pw.toml"
hash = "8d250e4781a41beb98270b2f36e042415067f92081c6fcf843d7ea89a61b4cdc"
metafile = true

[[files]]
file = "mods/no-chat-reports.pw.toml"
hash = "e94c47d7679c5a6a4a3deccaa7bba8f7c3961a70f6c03c32adc809d7135c87cc"
metafile = true

[[files]]
file = "mods/no-double-sneak.pw.toml"
hash = "db834fc92e54a4c688548de39cc0953a51fa9a56506a56ea2bbbbf6a2edf9c6a"
metafile = true

[[files]]
file = "mods/no-resource-pack-warnings.pw.toml"
hash = "da9ac20bdc1caa50ebec291429638780924e8a5060ec39abe085c7e6182b3a6f"
metafile = true

[[files]]
file = "mods/owo-lib.pw.toml"
hash = "3c79199e4f8a8221ae7095f45a83655fa3baebb59e4cab3d2544be52d1b29df6"
metafile = true

[[files]]
file = "mods/packcore.pw.toml"
hash = "528505879f1c92ec194b41bb53a7b34e53f126b1fee3df5e14e4a6757b5e0177"
metafile = true

[[files]]
file = "mods/particle-core.pw.toml"
hash = "35806b3163ce2405e55abcda320300fa7a133f2f67ad453c7d3631d68a5ba0e2"
metafile = true

[[files]]
file = "mods/placeholder-api.pw.toml"
hash = "799419e64ed42a8175333c541a08995fc4d84a2c6000877f60262fe55892e3ff"
metafile = true

[[files]]
file = "mods/reeses-sodium-options.pw.toml"
hash = "55a727cabdd9d6e84fb0232b49d0dfa207751002e7f1f63b959baa35e2f29868"
metafile = true

[[files]]
file = "mods/rei-search-bar-calculations.pw.toml"
hash = "6e7d10f3933c5e85b2ba9c5a7b0e550d5af9f2a0455483e54f1746584a742f2e"
metafile = true

[[files]]
file = "mods/rei.pw.toml"
hash = "f04be730a6dde5e7e3ce302260bc1a456a4e0fd57a00755d3992f9c0daafd21d"
metafile = true

[[files]]
file = "mods/sbt.pw.toml"
hash = "3709c90879c9c65e6fb3cc6a288ba2da0e214f60f17b1721d14133548e4eecd2"
metafile = true

[[files]]
file = "mods/scalablelux.pw.toml"
hash = "2cb94b8ba333302595808fee4d5b1a835fd1ceba87c87722eeaaf4ceb7e09121"
metafile = true

[[files]]
file = "mods/scaleme.pw.toml"
hash = "fa5c7a4931be169805c078bf860389cab3c1f05b1bb4d84cede26b12d822ce62"
metafile = true

[[files]]
file = "mods/sk1er-scrollable-tooltips.pw.toml"
hash = "7df906c0f5ee6d8bc2ce16eeb143f931897fb9705cc4bc5bba7e251f6ef9fd72"
metafile = true

[[files]]
file = "mods/skyblock-profile-viewer.pw.toml"
hash = "ce94f6c40a19c645a9aead8a60fd4e6ce6317ed2032f99e90a34c5c3961b16aa"
metafile = true

[[files]]
file = "mods/skyblockaddons-unofficial.pw.toml"
hash = "ccebed9beea247d724eb57aaee60ac175d01d4007eeb93dd3f48432783648baf"
metafile = true

[[files]]
file = "mods/skyblocker-liap.pw.toml"
hash = "026ba7785637e264e821f7fa61d8c3211c748c19e0be252a93416a183f058f44"
metafile = true

[[files]]
file = "mods/skyhanni.pw.toml"
hash = "7c888df1391d7e5e5ffce08d9982824dc66787e381cd4cc29e36968516ad4afd"
metafile = true

[[files]]
file = "mods/skyocean.pw.toml"
hash = "f3c66f62ed9925c0608cd23a59c8455b1558347a711e502878dd102fac1a8170"
metafile = true

[[files]]
file = "mods/sodium-extra.pw.toml"
hash = "abe9878dcb237d56e2ba70c17db8c721c6c2b8e62b241bc333539d5bc6be938f"
metafile = true

[[files]]
file = "mods/sodium-shadowy-path-blocks.pw.toml"
hash = "2d27a6e7c7e28a33b4e3d85106f80fd6629f060ec31a8be525f1c2ac9f769cf1"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "700caca572649f238e804258f79d25969031be3e1b01d0384eb54a13200caba6"
metafile = true

[[files]]
file = "mods/sound-controller.pw.toml"
hash = "5eb6c30f71d4b90b393612c6ca74e157b5544320f652bb397de165486685679a"
metafile = true

[[files]]
file = "mods/threadtweak.pw.toml"
hash = "ff0d87064f466d6dfa5151178cb805cea4169a6e85f47913b462758262a78024"
metafile = true

[[files]]
file = "mods/vistas.pw.toml"
hash = "633434fd0533b75e3ead8e8d6b44d327ca70a9e4c3a3a72b6b7f46d196222673"
metafile = true

[[files]]
file = "mods/vmp-fabric.pw.toml"
hash = "dee7712131e72105b1a9dafe6e103308e33023a4a48ec3b3868298d8d6c4ed6c"
metafile = true

[[files]]
file = "mods/wavey-capes.pw.toml"
hash = "db7ed475ed0ff75614a68bc62071d90197a532270d3863466bdef4ce9900911e"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "0de903f6957cf16eca63c7eca70d879b6d7c97d73f581659b8cf3441eff765d2"
metafile = true

[[files]]
file = "mods/zoomify.pw.toml"
hash = "c9a5dca078d983e94d629ca4bf402fff78e364e5b5365ff43373d77eec268432"
metafile = true

[[files]]
file = "resourcepacks/furfsky-reborn.pw.toml"
hash = "b56bb632dc2e82e66b7f477ae94b3586a18e9727996409e509e51a742a0f22a1"
metafile = true

[[files]]
file = "resourcepacks/hypixel-plus.pw.toml"
hash = "8fc9af99250f569b0a6208b4d856d83faebf93d956da3795f993da5679f8d072"
metafile = true

[[files]]
file = "resourcepacks/skyblock-dark-ui.pw.toml"
hash = "6e09ad2a763b2d00c30240079a7cdbc57765bc2e305ff215e2860a6cc2370b4a"
metafile = true
