name = "SkyBlock Enhanced"
author = "Kd_Gaming1"
version = "2.3.18"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d9712ce40dcbc6333d50be6d2ed0222a493866f903f48d006eee32f902ce9307"

[versions]
forge = "11.15.1.2318"
minecraft = "1.8.9"
