name = "SkyBlock Enhanced Modern Edition"
author = "Kd_Gaming1"
version = "0.3.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2dbad027aa2357f7c765a292192524868340832a64fdfdb78ea8bfd9af2095c8"

[versions]
fabric = "0.16.14"
minecraft = "1.21.5"
