name = "SkyBlock Enhanced Modern Edition"
author = "Kd_Gaming1"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f539ecec1090ef375f50db04d41cda55bdaf3d66272a7ad31e00f5eeaf016911"

[versions]
fabric = "0.16.14"
minecraft = "1.21.5"
