name = "SkyBlock Enhanced Modern Edition"
author = "Kd_Gaming1"
version = "1.2.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dd657c337de8b82dbf9e8d4fb10a31c7ee15abad4a32999000e99f0ed42e2469"

[versions]
fabric = "0.16.14"
minecraft = "1.21.5"
