name = "SkyBlock Enhanced Modern Edition"
author = "Kd_Gaming1"
version = "1.2.10"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6e62a1f4cacf157614d9c010869ce9bd16ebcb29a84464a00dc16e0000d5afa0"

[versions]
fabric = "0.17.1"
minecraft = "1.21.5"
