name = "SkyBlock Enhanced Modern Edition"
author = "Kd_Gaming1"
version = "1.2.20"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4a87a50e2e631897b9c41c4dcf8fca7b87c11ccaf869f9f3aebec59c23a9c299"

[versions]
fabric = "0.17.2"
minecraft = "1.21.5"
