name = "SkyBlock Enhanced Modern Edition"
author = "Kd_Gaming1"
version = "1.2.7"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "96a2ac24a843fc017abea7f5f790eb4b3711d276942a0da0811cbfdeddb05d23"

[versions]
fabric = "0.16.14"
minecraft = "1.21.5"
