name = "SkyBlock Enhanced Modern Edition"
author = "Kd_Gaming1"
version = "1.2.10"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9cc17a717a6fc96473212677cb97dc18ec32b5bb88dc4bba4d23e05c85f57372"

[versions]
fabric = "0.17.1"
minecraft = "1.21.5"
