name = "SkyBlock Enhanced Modern Edition"
author = "Kd_Gaming1"
version = "1.2.2"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8432c32a2fc2c3d859bf36f86b07bd4d6f40ba1c60a8d680b953680ae48d29b0"

[versions]
fabric = "0.16.14"
minecraft = "1.21.5"
