name = "SkyBlock Enhanced â€“ Modern Edition"
author = "Kd_Gaming1"
version = "0.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d1e7cf6df20da5e64b588c502e8c082d7fc1a1cbc1f811c97994e21c53adb238"

[versions]
fabric = "0.16.14"
minecraft = "1.21.5"
