name = "SkyBlock Enhanced Modern Edition"
author = "Kd_Gaming1"
version = "1.2.13"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ba8388b1e90b0ec89c0ab1b2b5db83de8d46597b804e604767dbd5853c2a30ca"

[versions]
fabric = "0.17.2"
minecraft = "1.21.5"
