name = "SkyBlock Enhanced â€“ Modern Edition"
author = "Kd_Gaming1"
version = "0.2.8"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ad745a6eecfeeae40db5c604b0f4c7654ef4e6c4a6665e0efa3a1b719206e1d5"

[versions]
fabric = "0.16.14"
minecraft = "1.21.5"
